version: "3.7"

services:
  db:
    ports:
      - "3306:3306"

  backend:
    volumes:
      - ./backend:/var/www/backend
      - ./config/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini

  proxy:
    volumes:
      - ./backend:/var/www/backend

